FROM node:21-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY "package.json" "pnpm-lock.yaml" ./
RUN pnpm install

COPY . .

EXPOSE 5173
EXPOSE 24678

CMD ["pnpm", "dev", "--host", "0.0.0.0"]