services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
    env_file:
      - .env
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
      - 15319:15319
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
volumes:
  node_modules: